### ISSUE TITLE
Can't handle periods in file names

### ISSUE THREAD

**Issue by rhk4360** [jonschlinkert/grunt-fixmyjs#12]
Hi,

Thanks for making this first and foremost.  The issue that I have is almost all of our js files have one or more periods in the file name and that causes issue when the result files are created.  

So, a.b.c.js would come out as a.js and I have a lot of files that start with a.  

I plan to parse files one by one anyway, but if the results are good I'd like to automate it a bit more in the future.

Thanks!
Ryan

**Comment by jonschlinkert** [comment]
I'm not sure how this project would have any effect on file names, since grunt is the system that handles reading and writing files. might want to check with that project. thanks
