### ISSUE TITLE
Can't set one tab indent

### ISSUE THREAD

**Issue by chindyaev** [jonschlinkert/grunt-fixmyjs#14]
Can I set indentation size to 1 tab?
Now I can only set options.indentpref either to 'spaces' (and it will be 2 spaces) or to 'tabs'(it will be 2 tabs).
But i'd like to have 1 tab indentation. How can I do it?

**Comment by jonschlinkert** [comment]
This is a fixmyjs issue. please see that repo for options. https://github.com/jshint/fixmyjs
