### ISSUE TITLE
code duplicates

### ISSUE THREAD

**Issue by giulianozorzi** [jonschlinkert/grunt-fixmyjs#19]
Hello,
I'm using the version 0.3.0 with the latest grunt 1.0.1 and grunt-vli 1.2.0, all installed by npm

my grunt task is the following:

``` js
fixmyjs: {
        options: {
          config: '.jshintrc',
          indentpref: 'spaces'
        },
        test: {
          files: [
            {
                expand: true, 
                cwd: 'static/js', 
                src: ['**/*.js'], 
                dest: 'static/js/', 
                ext: '.js'
            }
          ]
        }
      },
```

Sometimes (I could not find a way to replicate I get duplicated code (ie if the source file contains 

``` js
var a = true; 
```

I end up with 

``` js
var a = true;
var a = true;
```

the tasks I'm running are in order

``` js
fixmyjs
jshint
concat
uglify
```

Is there a way to determine what causes this and fix this behaviour ? As now I've changed the task so  the ext is changed to 

`ext: '.fixed.js'`

but I'd really like to fix my js files for good :)

thanks !

edited by @doowb: adding back ticks around code blocks for readability

**Comment by doowb** [comment]
@giulianozorzi this is probably an issue with [fixmyjs](https://github.com/jshint/fixmyjs). Check that repository and open an issue there if you can't solve it. This is just a grunt plugin to run [fixmyjs](https://github.com/jshint/fixmyjs) through a grunt configuration.

**Comment by jonschlinkert** [comment]
yeah this is an issue for fixmyjs. closing (thanks @doowb)
